---
title: "00 - Run all quarto documents of the projects"
subtitle: "R for Bio Data Science"
format: html
author: Mikkel Niklas Rasmussen (s193518)
date: "2023-11-08"
editor: visual
---

## Install required packages for entire project

```{r}
# Install here package
if (!requireNamespace("here", quietly = TRUE)) {
        install.packages("here", dependencies = TRUE)
}

# Install all required packages for the project via 
# the custom check_and_install_libraries() function
library("here")
source(here("R/99_proj_func.R"))
check_and_install_packages(dir_path=here("R"))
```

## Load libraries

```{r}
library("quarto")
```

```{r}
quarto_render(
  input = here("R/01_load.qmd"),
  output_file = "01_load.html"
)

file.rename(from =  here("results/R/01_load.html"),
            to =  here("results/01_load.html"))

quarto_render(
  input = here("R/02_clean.qmd"),
  output_file = "02_clean.html"
)

file.rename(from =  here("results/R/02_clean.html"),
            to =  here("results/02_clean.html"))

quarto_render(
  input = here("R/03_augment.qmd"),
  output_file = "03_augment.html"
)

file.rename(from =  here("results/R/03_augment.html"),
            to =  here("results/03_augment.html"))

```
