---
title: "01 - Loading data"
subtitle: "R for Bio Data Science"
format: html
author: Mikkel Niklas Rasmussen (s193518)
date: "2023-11-08"
editor: visual
---

## Load libraries

```{r}
library("tidyverse")
library("fs")
library("here")
```

```{r}
# Create _raw data folder directory
raw_folder <- dir_create(here("_raw"))

# List the urls needed for downloading the data
urls <- c(
  "https://datadryad.org/stash/downloads/file_stream/96050",
  "https://datadryad.org/stash/downloads/file_stream/96056",
  "https://datadryad.org/stash/downloads/file_stream/96052",
  "https://datadryad.org/stash/downloads/file_stream/96054",
  "https://datadryad.org/stash/downloads/file_stream/96051",
  "https://datadryad.org/stash/downloads/file_stream/96057",
  "https://datadryad.org/stash/downloads/file_stream/96053",
  "https://datadryad.org/stash/downloads/file_stream/96055",
  "https://datadryad.org/stash/downloads/file_stream/96059",
  "https://datadryad.org/stash/downloads/file_stream/96058"
)


# Create list of file names and add raw folder to filenames
filenames <- c(
  "gene_counts.txt",
  "intergenics.txt",
  "Introns.txt",
  "linc_KhalilGenes.txt",
  "README_for_gene_counts.txt",
  "README_for_intergenics.txt",
  "README_for_Introns.txt",
  "README_for_linc_KhalilGenes.txt",
  "README_for_recurrence.txt",
  "recurrence.txt"
)
raw_filenames <- str_c(raw_folder, "/", filenames)

# Downloads the files using purrr
walk2(urls, raw_filenames, download.file, mode = "wb")
```

## Write files to data folder

```{r}
# Create data data folder directory
data_folder <- dir_create(here("data"))

# Filter readme files from _raw before copying to data folder
raw_filenames <- raw_filenames |>
  str_subset("README", negate = TRUE)
filenames <- filenames |>
  str_subset("README", negate = TRUE)
data_filenames <- str_c(data_folder, "/", filenames)

# Copy files into data folder
file_copy(raw_filenames, data_filenames)
```
